version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: pixidos/coding-standards
    versions:
    - ">= 1.a, < 2"
