<?php
/**
 * Created by PhpStorm.
 * User: Ondra Votava
 * Date: 31.03.2017
 * Time: 14:02
 */

namespace PixidosTests\GPWebPay;

/**
 * Class GPWebPayTestCase
 * @package PixidosTests\GPWebPay
 * @author Ondra Votava <ondra.votava@pixidos.com>
 */

use Pixidos\GPWebPay\DI\GPWebPayExtension;
use Nette;
use Tester;

abstract class GPWebPayTestCase extends Tester\TestCase
{
	/**
	 * @var Nette\DI\Container
	 */
	private $container;

	/**
	 * @return Nette\DI\Container
	 */
	protected function prepareContainer()
	{
		$config = new Nette\Configurator();
		$config->setTempDirectory(TEMP_DIR);
		$config->addParameters(array('container' => array('class' => 'SystemContainer_' . md5(TEMP_DIR))));

		GPWebPayExtension::register($config);
		$config->addConfig(sprintf(__DIR__ . '/../webpay.config.neon'));

		return $this->container = $config->createContainer();
	}

	/**
	 * @return Nette\DI\Container
	 */
	public function getContainer()
	{
		if($this->container == NULL){
			throw new \LogicException('First need run ' .  get_called_class() .'::prepareContainer() to initialize the container.');
		}
		return $this->container;
	}

	protected function tearDown()
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
		//\Tester\Helpers::purge(TEMP_DIR);
		//rmdir(TEMP_DIR);
	}
}