# GitHub Action see https://github.com/shivammathur/setup-php
name: Unit Tests
on: [ push, pull_request ]
jobs:
    unit_tests:
        name: GPWebPay-core (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: [ '8.0', '8.1', '8.2' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: openssl, mbstring, json, intl, iconv, xml, tokenizer
                    coverage: xdebug #optional
            -   name: Composer dependencies
                uses: "ramsey/composer-install@v1"

            -   name: Run Tests
                run: vendor/bin/tester -p phpdbg tests -s -C --coverage ./coverage.xml --coverage-src ./src

            -   name: Upload Codecov
                uses: "codecov/codecov-action@v1"
                with:
                    files: ./coverage.xml
